version: '3'
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
          WWWGROUP: '${WWWGROUP:-1000}'
          WWWUSER: '${WWWUSER:-1000}' 
          USERNAME: '${USERNAME:-HermineGranger}' 
    image: beauty-bill
    volumes:
      - ./:/var/www/html
