<?php

namespace Tests;

use PHPUnit\Framework\TestCase;
use PrettyPdf\Partials\Invoice\Data\Item;
use PrettyPdf\Partials\Invoice\Data\PaymentInfo;
use PrettyPdf\PrettyPdf;

class PrettyPdfTestCase extends TestCase
{
    protected $storeOnly = false;

    /**
     * var BeautyBill
     */
    protected $prettyPdf;

    protected function getItemData()
    {
        $item = new Item();

        $item->description = 'A new currency';
        $item->quantity = 5;
        $item->name = 'Bitcoin';
        $item->unitPrice = 2031.23;

        return $item;
    }

    protected function getPaymentInfo()
    {
        $paymentInfoDate = new PaymentInfo();

        $paymentInfoDate->title = 'A really good title';
        $paymentInfoDate->description = 'A long description comes in here';
        $paymentInfoDate->bank = 'ING';
        $paymentInfoDate->bic = 'BICXXX';
        $paymentInfoDate->iban = 'DE42 4242 4242 4242 4242 24';
        $paymentInfoDate->name = 'Beauty Bill Creator';

        return $paymentInfoDate;
    }

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->prettyPdf = new PrettyPdf();
    }
    
    // One cannot compare the output content directly
    // with the file, because of metadata (creation date will differ).
    // As a workaround, we convert the pdfs to images
    // and compare the images.
    // Credit goes to:
    // https://gordonlesti.com/phpunit-compare-generated-pdf-files-with-imagick/
    protected function assertEqualPDFs($filename)
    {
        if ($this->storeOnly) {
            $this->storePDF($filename, $this->prettyPdf);
            return;
        }
        
        $content = $this->prettyPdf->output('s');
        
        $pdfContent = file_get_contents(__DIR__ . '/files/' . $filename);
        
        $assertedImagick = new \Imagick();
        $assertedImagick->readImageBlob($pdfContent);
        $assertedImagick->resetIterator();
        $assertedImagick = $assertedImagick->appendImages(true);

        $testImagick = new \Imagick();
        $testImagick->readImageBlob($content);
        $testImagick->resetIterator();
        $testImagick = $testImagick->appendImages(true);

        $diff = $assertedImagick->compareImages($testImagick, 1);
        $this->assertSame(0.0, $diff[1]);
    }

    protected function storePDF($filename, PrettyPdf $bill)
    {
        $bill->output('F', __DIR__ . '/files/' . $filename);
    }
}
